/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainWindow;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Administrator
 */
public class SubPanel_DiaryDesEditing extends javax.swing.JPanel {

    /**
     * Creates new form Panel_DiaryDesEditing
     */
    public SubPanel_DiaryDesEditing() {
        initComponents();
    }
    public void setDiaryTitle(String title){
        jL_title.setText(title);
        
    }
    
    public String getDiaryTitle(){
        return jL_title.getText();
    }
    public void setAllowComment(boolean f){
        jCheckBox2.setSelected(f);
        
    }
    
    public boolean getAllowComment(){
        return jCheckBox2.isSelected();
    }
    public void setDiaryType(String type){
        jcb_DiaryType.setSelectedItem(type);
    }
    public String getDiaryType(){
        return (String)jcb_DiaryType.getSelectedItem();
    }
    public void setTypeComboBox(List<String> types)
    {
        jcb_DiaryType.removeAllItems();
	for(String type:types)
	{
		jcb_DiaryType.addItem(type);		
	}
    }
    public JButton getPictureInsertButton()
    {
        return jb_InsertPicture;
    }
    public JButton getVoiceRecordButton()
    {
        return jb_RecordVoice;
    }
    public JButton getVoicePlayButton()
    {
        return jb_PlayVoice;
    }
    public JButton getDiarySaveButton()
    {
        return jb_SaveUpdate;
    }
    public void setDiaryVisibleType(int type){
        if(type==2)
            jCheckBox2.setSelected(true);
        else if(type==0)
            jCheckBox2.setSelected(false);
        else
            ;
    }
     public int getDiaryVisibleType(){
        if(jCheckBox2.isSelected())
            return 2;
        else
            return 0;
    }
    public JButton getCancelButton()
    {
        return jb_Cancel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_title = new javax.swing.JTextField();
        jb_SaveUpdate = new javax.swing.JButton();
        jb_PlayVoice = new javax.swing.JButton();
        jb_RecordVoice = new javax.swing.JButton();
        jb_InsertPicture = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jcb_DiaryType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jb_Cancel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jL_title.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N

        jb_SaveUpdate.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jb_SaveUpdate.setText("保存");

        jb_PlayVoice.setText("播放");

        jb_RecordVoice.setText("录音");

        jb_InsertPicture.setText("插入图片");

        jCheckBox2.setText("允许评论");

        jcb_DiaryType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("分类：");

        jLabel7.setText("标题：");
        jLabel7.setToolTipText("");

        jb_Cancel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jb_Cancel.setText("取消");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jL_title, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_DiaryType, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_InsertPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_RecordVoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_PlayVoice)
                        .addGap(60, 60, 60)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_SaveUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Cancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jL_title, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jcb_DiaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_InsertPicture)
                    .addComponent(jb_RecordVoice)
                    .addComponent(jb_PlayVoice)
                    .addComponent(jb_SaveUpdate)
                    .addComponent(jCheckBox2)
                    .addComponent(jb_Cancel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JTextField jL_title;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb_Cancel;
    private javax.swing.JButton jb_InsertPicture;
    private javax.swing.JButton jb_PlayVoice;
    private javax.swing.JButton jb_RecordVoice;
    private javax.swing.JButton jb_SaveUpdate;
    private javax.swing.JComboBox jcb_DiaryType;
    // End of variables declaration//GEN-END:variables
}
